// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfileLearn.Data;

namespace ProfileLearn.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProfileLearn.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Secret")
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HistoryEntityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProfileLearn.Entities.HistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedDated")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Secret")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("EntitesHisotry");
                });

            modelBuilder.Entity("ProfileLearn.Entities.AppUser", b =>
                {
                    b.HasOne("ProfileLearn.Entities.HistoryEntity", "HistoryEntity")
                        .WithMany()
                        .HasForeignKey("HistoryEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
